on:
  workflow_dispatch:
  pull_request:
    branches: [main]
name: Bicep plan
jobs:
  build-and-plan:    
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Test Deployment Bicep file in DEV
    - name: Test Dev Deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: ./main.bicep
        parameters: ./Parameters/dev/dev.azuredeploy.parameters.json
        failOnStdErr: false
        additionalArguments: "--what-if"
