on:
  push:
    branches: [main]
name: Bicep_Deploy

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Test Deployment Bicep file
    - name: Dev Deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: ./main.bicep
        #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        parameters: ./Parameters/dev/dev.azuredeploy.parameters.json
        failOnStdErr: false
  build-and-deploy-prd:
    runs-on: ubuntu-latest
    environment: prd
    needs: build-and-deploy-dev
    steps:
        # Checkout code
    - uses: actions/checkout@main
        # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Test Deployment Bicep file
    - name: Prd Deployment
      uses: azure/arm-deploy@v1      
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        template: ./main.bicep
        #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        parameters: ./Parameters/prd/prd.azuredeploy.parameters.json
        failOnStdErr: false
      
