on:
  pull_request:
    branches: [main]
name: Azure ARM
jobs:
  build-and-plan:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Test Deployment Bicep file
    - name: Test Dev Deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: ./Parameters/Dev/dev.azuredeploy.parameters.json
        failOnStdErr: false
        additionalArguments: "--what-if"
