on:
  push:
    branches: [main]
name: Bicep_Deploy

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Test Deployment Bicep file
    - name: Dev Deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ var.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ var.AZURE_RG }}
        template: ./main.bicep
        #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        parameters: ./Parameters/Dev/dev.azuredeploy.parameters.json
        failOnStdErr: false
  build-and-deploy-prd:
    runs-on: ubuntu-latest
    environment: prd
    needs: build-and-deploy-dev
    steps:

        # Checkout code
    - uses: actions/checkout@main

        # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Test Deployment Bicep file
    - name: Prd Deployment
      uses: azure/arm-deploy@v1      
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        parameters: ./Parameters/Prd/prd.azuredeploy.parameters.json
        failOnStdErr: false
      
